services:
  backend:
    build: ./backend
    container_name: backend-acearia
    ports:
      - "8035:8000"
    environment:
      - RTSP_URL=rtsp://admin:eletricasnb2021@10.6.51.75:554/cam/realmonitor?channel=1&subtype=1
    volumes:
      - ./backend:/app
      - ./models:/app/models
    networks:
      - acearia-net
    command: uvicorn main:app --host 0.0.0.0 --port 8000 

  frontend:
    build: ./frontend
    container_name: ui-acearia
    ports:
      - "8025:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - acearia-net

networks:
  acearia-net:
    driver: bridge
